classdef DroneTaskControlRequest < ros.Message
    %DroneTaskControlRequest MATLAB implementation of djiros/DroneTaskControlRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/DroneTaskControlRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a3d0779d88f1c88b74d6da1390832b1b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        TASKGOHOME = uint8(1)
        TASKTAKEOFF = uint8(4)
        TASKLAND = uint8(6)
    end
    
    properties (Dependent)
        Task
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Task'} % List of non-constant message properties
        ROSPropertyList = {'task'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = DroneTaskControlRequest(msg)
            %DroneTaskControlRequest Construct the message object DroneTaskControlRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function task = get.Task(obj)
            %get.Task Get the value for property Task
            task = typecast(int8(obj.JavaMessage.getTask), 'uint8');
        end
        
        function set.Task(obj, task)
            %set.Task Set the value for property Task
            validateattributes(task, {'numeric'}, {'nonempty', 'scalar'}, 'DroneTaskControlRequest', 'Task');
            
            obj.JavaMessage.setTask(task);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Task = obj.Task;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Task = strObj.Task;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Task = obj.Task;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.DroneTaskControlRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.DroneTaskControlRequest;
            obj.reload(strObj);
        end
    end
end
