classdef MFIOConfigRequest < ros.Message
    %MFIOConfigRequest MATLAB implementation of djiros/MFIOConfigRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MFIOConfigRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ad06bda475c7f13453680ee626114de0' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        MODEPWMOUT = uint8(0)
        MODEGPIOOUT = uint8(2)
        MODEGPIOIN = uint8(3)
        MODEADC = uint8(4)
    end
    
    properties (Dependent)
        Mode
        Channel
        InitOnTimeUs
        PwmFreq
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Channel', 'InitOnTimeUs', 'Mode', 'PwmFreq'} % List of non-constant message properties
        ROSPropertyList = {'channel', 'init_on_time_us', 'mode', 'pwm_freq'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MFIOConfigRequest(msg)
            %MFIOConfigRequest Construct the message object MFIOConfigRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function mode = get.Mode(obj)
            %get.Mode Get the value for property Mode
            mode = typecast(int8(obj.JavaMessage.getMode), 'uint8');
        end
        
        function set.Mode(obj, mode)
            %set.Mode Set the value for property Mode
            validateattributes(mode, {'numeric'}, {'nonempty', 'scalar'}, 'MFIOConfigRequest', 'Mode');
            
            obj.JavaMessage.setMode(mode);
        end
        
        function channel = get.Channel(obj)
            %get.Channel Get the value for property Channel
            channel = typecast(int8(obj.JavaMessage.getChannel), 'uint8');
        end
        
        function set.Channel(obj, channel)
            %set.Channel Set the value for property Channel
            validateattributes(channel, {'numeric'}, {'nonempty', 'scalar'}, 'MFIOConfigRequest', 'Channel');
            
            obj.JavaMessage.setChannel(channel);
        end
        
        function initontimeus = get.InitOnTimeUs(obj)
            %get.InitOnTimeUs Get the value for property InitOnTimeUs
            initontimeus = typecast(int32(obj.JavaMessage.getInitOnTimeUs), 'uint32');
        end
        
        function set.InitOnTimeUs(obj, initontimeus)
            %set.InitOnTimeUs Set the value for property InitOnTimeUs
            validateattributes(initontimeus, {'numeric'}, {'nonempty', 'scalar'}, 'MFIOConfigRequest', 'InitOnTimeUs');
            
            obj.JavaMessage.setInitOnTimeUs(initontimeus);
        end
        
        function pwmfreq = get.PwmFreq(obj)
            %get.PwmFreq Get the value for property PwmFreq
            pwmfreq = typecast(int16(obj.JavaMessage.getPwmFreq), 'uint16');
        end
        
        function set.PwmFreq(obj, pwmfreq)
            %set.PwmFreq Set the value for property PwmFreq
            validateattributes(pwmfreq, {'numeric'}, {'nonempty', 'scalar'}, 'MFIOConfigRequest', 'PwmFreq');
            
            obj.JavaMessage.setPwmFreq(pwmfreq);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Mode = obj.Mode;
            cpObj.Channel = obj.Channel;
            cpObj.InitOnTimeUs = obj.InitOnTimeUs;
            cpObj.PwmFreq = obj.PwmFreq;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Mode = strObj.Mode;
            obj.Channel = strObj.Channel;
            obj.InitOnTimeUs = strObj.InitOnTimeUs;
            obj.PwmFreq = strObj.PwmFreq;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Mode = obj.Mode;
            strObj.Channel = obj.Channel;
            strObj.InitOnTimeUs = obj.InitOnTimeUs;
            strObj.PwmFreq = obj.PwmFreq;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MFIOConfigRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MFIOConfigRequest;
            obj.reload(strObj);
        end
    end
end
