classdef MissionWaypointAction < ros.Message
    %MissionWaypointAction MATLAB implementation of djiros/MissionWaypointAction
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MissionWaypointAction' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '498ad6e0be62eb526de719adc0d881d5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        ActionRepeat
        CommandList
        CommandParameter
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ActionRepeat', 'CommandList', 'CommandParameter'} % List of non-constant message properties
        ROSPropertyList = {'action_repeat', 'command_list', 'command_parameter'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionWaypointAction(msg)
            %MissionWaypointAction Construct the message object MissionWaypointAction
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function actionrepeat = get.ActionRepeat(obj)
            %get.ActionRepeat Get the value for property ActionRepeat
            actionrepeat = typecast(int8(obj.JavaMessage.getActionRepeat), 'uint8');
        end
        
        function set.ActionRepeat(obj, actionrepeat)
            %set.ActionRepeat Set the value for property ActionRepeat
            validateattributes(actionrepeat, {'numeric'}, {'nonempty', 'scalar'}, 'MissionWaypointAction', 'ActionRepeat');
            
            obj.JavaMessage.setActionRepeat(actionrepeat);
        end
        
        function commandlist = get.CommandList(obj)
            %get.CommandList Get the value for property CommandList
            javaArray = obj.JavaMessage.getCommandList;
            array = obj.readJavaArray(javaArray, 'uint8');
            commandlist = uint8(array);
        end
        
        function set.CommandList(obj, commandlist)
            %set.CommandList Set the value for property CommandList
            validateattributes(commandlist, {'numeric'}, {'vector', 'numel', 16}, 'MissionWaypointAction', 'CommandList');
            
            javaArray = obj.JavaMessage.getCommandList;
            array = obj.writeJavaArray(commandlist, javaArray, 'uint8');
            obj.JavaMessage.setCommandList(array);
        end
        
        function commandparameter = get.CommandParameter(obj)
            %get.CommandParameter Get the value for property CommandParameter
            javaArray = obj.JavaMessage.getCommandParameter;
            array = obj.readJavaArray(javaArray, 'int16');
            commandparameter = int16(array);
        end
        
        function set.CommandParameter(obj, commandparameter)
            %set.CommandParameter Set the value for property CommandParameter
            validateattributes(commandparameter, {'numeric'}, {'vector', 'numel', 16}, 'MissionWaypointAction', 'CommandParameter');
            
            javaArray = obj.JavaMessage.getCommandParameter;
            array = obj.writeJavaArray(commandparameter, javaArray, 'int16');
            obj.JavaMessage.setCommandParameter(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ActionRepeat = obj.ActionRepeat;
            cpObj.CommandList = obj.CommandList;
            cpObj.CommandParameter = obj.CommandParameter;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ActionRepeat = strObj.ActionRepeat;
            obj.CommandList = strObj.CommandList;
            obj.CommandParameter = strObj.CommandParameter;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ActionRepeat = obj.ActionRepeat;
            strObj.CommandList = obj.CommandList;
            strObj.CommandParameter = obj.CommandParameter;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MissionWaypointAction.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MissionWaypointAction;
            obj.reload(strObj);
        end
    end
end
