classdef MissionStatusResponse < ros.Message
    %MissionStatusResponse MATLAB implementation of djiros/MissionStatusResponse
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MissionStatusResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '76ed0b909c77c6ce98df135419939be9' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        WaypointMissionCount
        HotpointMissionCount
    end
    
    properties (Constant, Hidden)
        PropertyList = {'HotpointMissionCount', 'WaypointMissionCount'} % List of non-constant message properties
        ROSPropertyList = {'hotpoint_mission_count', 'waypoint_mission_count'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionStatusResponse(msg)
            %MissionStatusResponse Construct the message object MissionStatusResponse
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function waypointmissioncount = get.WaypointMissionCount(obj)
            %get.WaypointMissionCount Get the value for property WaypointMissionCount
            waypointmissioncount = typecast(int8(obj.JavaMessage.getWaypointMissionCount), 'uint8');
        end
        
        function set.WaypointMissionCount(obj, waypointmissioncount)
            %set.WaypointMissionCount Set the value for property WaypointMissionCount
            validateattributes(waypointmissioncount, {'numeric'}, {'nonempty', 'scalar'}, 'MissionStatusResponse', 'WaypointMissionCount');
            
            obj.JavaMessage.setWaypointMissionCount(waypointmissioncount);
        end
        
        function hotpointmissioncount = get.HotpointMissionCount(obj)
            %get.HotpointMissionCount Get the value for property HotpointMissionCount
            hotpointmissioncount = typecast(int8(obj.JavaMessage.getHotpointMissionCount), 'uint8');
        end
        
        function set.HotpointMissionCount(obj, hotpointmissioncount)
            %set.HotpointMissionCount Set the value for property HotpointMissionCount
            validateattributes(hotpointmissioncount, {'numeric'}, {'nonempty', 'scalar'}, 'MissionStatusResponse', 'HotpointMissionCount');
            
            obj.JavaMessage.setHotpointMissionCount(hotpointmissioncount);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.WaypointMissionCount = obj.WaypointMissionCount;
            cpObj.HotpointMissionCount = obj.HotpointMissionCount;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.WaypointMissionCount = strObj.WaypointMissionCount;
            obj.HotpointMissionCount = strObj.HotpointMissionCount;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.WaypointMissionCount = obj.WaypointMissionCount;
            strObj.HotpointMissionCount = obj.HotpointMissionCount;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MissionStatusResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MissionStatusResponse;
            obj.reload(strObj);
        end
    end
end
