classdef MissionWpGetInfoResponse < ros.Message
    %MissionWpGetInfoResponse MATLAB implementation of djiros/MissionWpGetInfoResponse
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MissionWpGetInfoResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f07d03dfb16f6e1aa2bdafc8d4e220df' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        DjirosMissionWaypointTaskClass = ros.msg.internal.MessageFactory.getClassForType('djiros/MissionWaypointTask') % Dispatch to MATLAB class for message type djiros/MissionWaypointTask
    end
    
    properties (Dependent)
        WaypointTask
    end
    
    properties (Access = protected)
        Cache = struct('WaypointTask', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'WaypointTask'} % List of non-constant message properties
        ROSPropertyList = {'waypoint_task'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionWpGetInfoResponse(msg)
            %MissionWpGetInfoResponse Construct the message object MissionWpGetInfoResponse
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function waypointtask = get.WaypointTask(obj)
            %get.WaypointTask Get the value for property WaypointTask
            if isempty(obj.Cache.WaypointTask)
                obj.Cache.WaypointTask = feval(obj.DjirosMissionWaypointTaskClass, obj.JavaMessage.getWaypointTask);
            end
            waypointtask = obj.Cache.WaypointTask;
        end
        
        function set.WaypointTask(obj, waypointtask)
            %set.WaypointTask Set the value for property WaypointTask
            validateattributes(waypointtask, {obj.DjirosMissionWaypointTaskClass}, {'nonempty', 'scalar'}, 'MissionWpGetInfoResponse', 'WaypointTask');
            
            obj.JavaMessage.setWaypointTask(waypointtask.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.WaypointTask)
                obj.Cache.WaypointTask.setJavaObject(waypointtask.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.WaypointTask = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.WaypointTask = copy(obj.WaypointTask);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.WaypointTask = feval([obj.DjirosMissionWaypointTaskClass '.loadobj'], strObj.WaypointTask);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.WaypointTask = saveobj(obj.WaypointTask);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MissionWpGetInfoResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MissionWpGetInfoResponse;
            obj.reload(strObj);
        end
    end
end
