classdef MissionHpUpdateYawRateRequest < ros.Message
    %MissionHpUpdateYawRateRequest MATLAB implementation of djiros/MissionHpUpdateYawRateRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MissionHpUpdateYawRateRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '5e07211af04442e78da518f6609aac85' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        YawRate
        Direction
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Direction', 'YawRate'} % List of non-constant message properties
        ROSPropertyList = {'direction', 'yaw_rate'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionHpUpdateYawRateRequest(msg)
            %MissionHpUpdateYawRateRequest Construct the message object MissionHpUpdateYawRateRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function yawrate = get.YawRate(obj)
            %get.YawRate Get the value for property YawRate
            yawrate = single(obj.JavaMessage.getYawRate);
        end
        
        function set.YawRate(obj, yawrate)
            %set.YawRate Set the value for property YawRate
            validateattributes(yawrate, {'numeric'}, {'nonempty', 'scalar'}, 'MissionHpUpdateYawRateRequest', 'YawRate');
            
            obj.JavaMessage.setYawRate(yawrate);
        end
        
        function direction = get.Direction(obj)
            %get.Direction Get the value for property Direction
            direction = typecast(int8(obj.JavaMessage.getDirection), 'uint8');
        end
        
        function set.Direction(obj, direction)
            %set.Direction Set the value for property Direction
            validateattributes(direction, {'numeric'}, {'nonempty', 'scalar'}, 'MissionHpUpdateYawRateRequest', 'Direction');
            
            obj.JavaMessage.setDirection(direction);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.YawRate = obj.YawRate;
            cpObj.Direction = obj.Direction;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.YawRate = strObj.YawRate;
            obj.Direction = strObj.Direction;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.YawRate = obj.YawRate;
            strObj.Direction = obj.Direction;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MissionHpUpdateYawRateRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MissionHpUpdateYawRateRequest;
            obj.reload(strObj);
        end
    end
end
