classdef MissionHpUploadRequest < ros.Message
    %MissionHpUploadRequest MATLAB implementation of djiros/MissionHpUploadRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/MissionHpUploadRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e36e66ca170c4d03ee023ad56c6bb5a0' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        DjirosMissionHotpointTaskClass = ros.msg.internal.MessageFactory.getClassForType('djiros/MissionHotpointTask') % Dispatch to MATLAB class for message type djiros/MissionHotpointTask
    end
    
    properties (Dependent)
        HotpointTask
    end
    
    properties (Access = protected)
        Cache = struct('HotpointTask', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'HotpointTask'} % List of non-constant message properties
        ROSPropertyList = {'hotpoint_task'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MissionHpUploadRequest(msg)
            %MissionHpUploadRequest Construct the message object MissionHpUploadRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function hotpointtask = get.HotpointTask(obj)
            %get.HotpointTask Get the value for property HotpointTask
            if isempty(obj.Cache.HotpointTask)
                obj.Cache.HotpointTask = feval(obj.DjirosMissionHotpointTaskClass, obj.JavaMessage.getHotpointTask);
            end
            hotpointtask = obj.Cache.HotpointTask;
        end
        
        function set.HotpointTask(obj, hotpointtask)
            %set.HotpointTask Set the value for property HotpointTask
            validateattributes(hotpointtask, {obj.DjirosMissionHotpointTaskClass}, {'nonempty', 'scalar'}, 'MissionHpUploadRequest', 'HotpointTask');
            
            obj.JavaMessage.setHotpointTask(hotpointtask.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.HotpointTask)
                obj.Cache.HotpointTask.setJavaObject(hotpointtask.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.HotpointTask = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.HotpointTask = copy(obj.HotpointTask);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.HotpointTask = feval([obj.DjirosMissionHotpointTaskClass '.loadobj'], strObj.HotpointTask);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.HotpointTask = saveobj(obj.HotpointTask);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.MissionHpUploadRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.MissionHpUploadRequest;
            obj.reload(strObj);
        end
    end
end
