classdef SDKControlAuthorityRequest < ros.Message
    %SDKControlAuthorityRequest MATLAB implementation of djiros/SDKControlAuthorityRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/SDKControlAuthorityRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4be067264420fcea65acedecc46466bd' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        RELEASECONTROL = uint8(0)
        REQUESTCONTROL = uint8(1)
    end
    
    properties (Dependent)
        ControlEnable
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ControlEnable'} % List of non-constant message properties
        ROSPropertyList = {'control_enable'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SDKControlAuthorityRequest(msg)
            %SDKControlAuthorityRequest Construct the message object SDKControlAuthorityRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function controlenable = get.ControlEnable(obj)
            %get.ControlEnable Get the value for property ControlEnable
            controlenable = typecast(int8(obj.JavaMessage.getControlEnable), 'uint8');
        end
        
        function set.ControlEnable(obj, controlenable)
            %set.ControlEnable Set the value for property ControlEnable
            validateattributes(controlenable, {'numeric'}, {'nonempty', 'scalar'}, 'SDKControlAuthorityRequest', 'ControlEnable');
            
            obj.JavaMessage.setControlEnable(controlenable);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.ControlEnable = obj.ControlEnable;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ControlEnable = strObj.ControlEnable;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ControlEnable = obj.ControlEnable;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.SDKControlAuthorityRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.SDKControlAuthorityRequest;
            obj.reload(strObj);
        end
    end
end
