classdef SetHardSyncRequest < ros.Message
    %SetHardSyncRequest MATLAB implementation of djiros/SetHardSyncRequest
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'djiros/SetHardSyncRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '055883b322dfe2d79dcba9762ea2d6d4' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Frequency
        Tag
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Frequency', 'Tag'} % List of non-constant message properties
        ROSPropertyList = {'frequency', 'tag'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetHardSyncRequest(msg)
            %SetHardSyncRequest Construct the message object SetHardSyncRequest
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function frequency = get.Frequency(obj)
            %get.Frequency Get the value for property Frequency
            frequency = typecast(int32(obj.JavaMessage.getFrequency), 'uint32');
        end
        
        function set.Frequency(obj, frequency)
            %set.Frequency Set the value for property Frequency
            validateattributes(frequency, {'numeric'}, {'nonempty', 'scalar'}, 'SetHardSyncRequest', 'Frequency');
            
            obj.JavaMessage.setFrequency(frequency);
        end
        
        function tag = get.Tag(obj)
            %get.Tag Get the value for property Tag
            tag = typecast(int16(obj.JavaMessage.getTag), 'uint16');
        end
        
        function set.Tag(obj, tag)
            %set.Tag Set the value for property Tag
            validateattributes(tag, {'numeric'}, {'nonempty', 'scalar'}, 'SetHardSyncRequest', 'Tag');
            
            obj.JavaMessage.setTag(tag);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Frequency = obj.Frequency;
            cpObj.Tag = obj.Tag;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Frequency = strObj.Frequency;
            obj.Tag = strObj.Tag;
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Frequency = obj.Frequency;
            strObj.Tag = obj.Tag;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.djiros.SetHardSyncRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.djiros.SetHardSyncRequest;
            obj.reload(strObj);
        end
    end
end
