classdef N3CtrlState < ros.Message
    %N3CtrlState MATLAB implementation of n3ctrl/N3CtrlState
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'n3ctrl/N3CtrlState' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8d831b9cebf12bffeb3ffe57c81265b2' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        STATEDIRECTCTRL = uint8(0)
        STATEJSCTRL = uint8(1)
        STATEJSNOCTRL = uint8(2)
        STATEJSRESETPOSCTRL = uint8(3)
        STATECMDHOVER = uint8(4)
        STATECMDCTRL = uint8(5)
        STATECMDNOCTRL = uint8(6)
        STATECMDRESETPOSCTRL = uint8(7)
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        State
        LastTrajId
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'LastTrajId', 'State'} % List of non-constant message properties
        ROSPropertyList = {'header', 'last_traj_id', 'state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = N3CtrlState(msg)
            %N3CtrlState Construct the message object N3CtrlState
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'N3CtrlState', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function state = get.State(obj)
            %get.State Get the value for property State
            state = typecast(int8(obj.JavaMessage.getState), 'uint8');
        end
        
        function set.State(obj, state)
            %set.State Set the value for property State
            validateattributes(state, {'numeric'}, {'nonempty', 'scalar'}, 'N3CtrlState', 'State');
            
            obj.JavaMessage.setState(state);
        end
        
        function lasttrajid = get.LastTrajId(obj)
            %get.LastTrajId Get the value for property LastTrajId
            lasttrajid = typecast(int32(obj.JavaMessage.getLastTrajId), 'uint32');
        end
        
        function set.LastTrajId(obj, lasttrajid)
            %set.LastTrajId Set the value for property LastTrajId
            validateattributes(lasttrajid, {'numeric'}, {'nonempty', 'scalar'}, 'N3CtrlState', 'LastTrajId');
            
            obj.JavaMessage.setLastTrajId(lasttrajid);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.State = obj.State;
            cpObj.LastTrajId = obj.LastTrajId;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.State = strObj.State;
            obj.LastTrajId = strObj.LastTrajId;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.State = obj.State;
            strObj.LastTrajId = obj.LastTrajId;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.n3ctrl.N3CtrlState.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.n3ctrl.N3CtrlState;
            obj.reload(strObj);
        end
    end
end
