classdef SwarmOdometry < ros.Message
    %SwarmOdometry MATLAB implementation of quadrotor_msgs/SwarmOdometry
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'quadrotor_msgs/SwarmOdometry' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '381c857708dd3343b90aa75a62dbf0ae' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        NavMsgsOdometryClass = ros.msg.internal.MessageFactory.getClassForType('nav_msgs/Odometry') % Dispatch to MATLAB class for message type nav_msgs/Odometry
    end
    
    properties (Dependent)
        Odom
        Name
    end
    
    properties (Access = protected)
        Cache = struct('Odom', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Name', 'Odom'} % List of non-constant message properties
        ROSPropertyList = {'name', 'odom'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SwarmOdometry(msg)
            %SwarmOdometry Construct the message object SwarmOdometry
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function odom = get.Odom(obj)
            %get.Odom Get the value for property Odom
            if isempty(obj.Cache.Odom)
                obj.Cache.Odom = feval(obj.NavMsgsOdometryClass, obj.JavaMessage.getOdom);
            end
            odom = obj.Cache.Odom;
        end
        
        function set.Odom(obj, odom)
            %set.Odom Set the value for property Odom
            validateattributes(odom, {obj.NavMsgsOdometryClass}, {'nonempty', 'scalar'}, 'SwarmOdometry', 'Odom');
            
            obj.JavaMessage.setOdom(odom.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Odom)
                obj.Cache.Odom.setJavaObject(odom.getJavaObject);
            end
        end
        
        function name = get.Name(obj)
            %get.Name Get the value for property Name
            name = char(obj.JavaMessage.getName);
        end
        
        function set.Name(obj, name)
            %set.Name Set the value for property Name
            name = convertStringsToChars(name);
            
            validateattributes(name, {'char', 'string'}, {}, 'SwarmOdometry', 'Name');
            
            obj.JavaMessage.setName(name);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Odom = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Name = obj.Name;
            
            % Recursively copy compound properties
            cpObj.Odom = copy(obj.Odom);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Name = strObj.Name;
            obj.Odom = feval([obj.NavMsgsOdometryClass '.loadobj'], strObj.Odom);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Name = obj.Name;
            strObj.Odom = saveobj(obj.Odom);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.quadrotor_msgs.SwarmOdometry.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.quadrotor_msgs.SwarmOdometry;
            obj.reload(strObj);
        end
    end
end
